name: env
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-build
  - pip
  - python
  - setuptools
  - bedtools
  - bedops
  - samtools
  - ucsc-bedtogenepred
  - ucsc-genepredtogtf
  - pygenometracks
  - hicexplorer
  - ipywidgets
  - plotly
  - deeptools
  - nodejs
  - pip:
    - setuptools
    - gnureadline
    - numpy
    - jupyter
    - jupyterlab
    - ipywidgets
    - argparse
    - pytest
    - pyensembl
    - pyliftover
    - h5py
