name: env
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-build
  - pip
  - python
  - setuptools
  - samtools
  - spades
  - mafft
  - pip:
    - setuptools
    - gnureadline
    - biopython
    - jupyter
    - jupyterlab
    - ipywidgets
    - argparse
