name: env
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-build
  - pip
  - python
  - setuptools
  - samtools
  - cmake
  - salmon
  - sra-tools
  - numpy
  - pip:
    - setuptools
    - gnureadline
    - jupyter
    - jupyterlab
    - ipywidgets
    - argparse
